### ISSUE TITLE
第2章词语搭配&Typo

### ISSUE THREAD

**Issue by dontpanic92** [changkun/modern-cpp-tutorial#10]
https://github.com/changkun/modern-cpp-tutorial/blob/8317c2bf00d9ee72a1988f82cfe4707aac5a8f60/book/02-usability.md#L26 

违反与直观搭配似乎不太合适

违反 直觉
违反（直观的）印象

----

https://github.com/changkun/modern-cpp-tutorial/blob/8317c2bf00d9ee72a1988f82cfe4707aac5a8f60/book/02-usability.md#L114 

回 / 会

----

https://github.com/changkun/modern-cpp-tutorial/blob/8317c2bf00d9ee72a1988f82cfe4707aac5a8f60/book/02-usability.md#L719 

以下 / 一下

**Comment by changkun** [comment]
非常感谢指出相关错误，内容已修复
