### ISSUE TITLE
3.3 中 原始字面量不一定是右值

### ISSUE THREAD

**Issue by cathaysia** [changkun/modern-cpp-tutorial#102]
## 实际描述

- 文件路径：例如，book/zh-cn/03-runtime.md
- 原文段落：

```
运算表达式产生的临时变量、 原始字面量、Lambda 表达式都属于纯右值。
```

## 原文表意不准确：

原始字面量并不一定是右值，比如 字符字面量，字符字面量可以被取地址，是一个左值。

参见：https://en.cppreference.com/w/cpp/language/value_category

**Comment by cathaysia** [comment]
更加糟糕的是，在类中的字符字面量是一个右值：

```cpp
class Parent{
char* s = &"hello"; // 此时 "hello" 为右值，无法取地址，无法通过编译
}

int main(){
    &“hello”; // 此时"hello"为左值，可以去地址，可以通过编译
}

```

**Comment by changkun** [comment]
PR welcome
