### ISSUE TITLE
笔误. 第 5 章 智能指针与内存管理   ->  std::end;

### ISSUE THREAD

**Issue by lsz7575** [changkun/modern-cpp-tutorial#104]
## Actual Description

- File Path: for example, `book/zh-cn/05-pointers.md`
- Original paragraph:

## 实际描述

- 文件路径：例如，book/zh-cn/05-pointers.md
- 原文段落：

```
复制原文段落

std::cout << "A 被销毁" << std::end;
std::cout << "B 被销毁" << std::end;
```

## 预期描述
```
修改后的段落

std::cout << "A 被销毁" << std::endl;
std::cout << "B 被销毁" << std::endl;
```

## 附图

必要时，请附上相关截图

**Comment by changkun** [comment]
PR welcome
