### ISSUE TITLE
Wrong Nomenclature Name for Venn Diagrams

### ISSUE THREAD

**Issue by Anmol-Sharma** [changkun/modern-cpp-tutorial#113]
There is a minor mistake on page 11 of the book. The name used for the type of diagram in use is wrong.

Original Line :-
```
The Wayne diagram in Figure 1.2 roughly answers the C and C++ related compatibility.
```

Expected Line :-
```
The Venn diagram in Figure 1.2 roughly answers the C and C++ related compatibility.
```

Reference : https://en.wikipedia.org/wiki/Venn_diagram

**Comment by changkun** [comment]
Thanks for the report.
