### ISSUE TITLE
想咨询一下 modern-cpp 网站用的是什么主题？

### ISSUE THREAD

**Issue by halfrost** [changkun/modern-cpp-tutorial#119]
长坤，您好，想问问您，modern-cpp 网站用的是什么主题呀？另外还想问问 go-under-the-hood 这个网站用的什么主题呢？

> 本来想在 go-under-the-hood 那边问问，但是被 Archive 了，只能合并在这边一起问您了。(另外好像发邮件给您，好像一直没有回复，不知道邮件是不是进了垃圾箱了)

**Comment by changkun** [comment]
您好，modern-cpp 和 go-under-the-hood 的网站主题都是自行定制和编写的，相关代码在仓库中均有开源。

遵守项目所使用开源协议的条件下允许其他用途。

**Comment by halfrost** [comment]
知道啦，感谢您的回答~
