### ISSUE TITLE
Providing English Version

### ISSUE THREAD

**Issue by reinismu** [changkun/modern-cpp-tutorial#12]
Was wondering what you would suggest

**Comment by trevor-vincent** [comment]
IMO google-chrome's page translation works really well on this book for the text, but it unfortunately tries to translate the code snippets so watch out.

**Comment by changkun** [comment]
Hi there, thanks for your interests :)

Good news is, translate this book into English is my next step after it fully supports C++17.

**Comment by azjkjensen** [comment]
Hey I don't know Chinese but I'd be happy to offer help with reviewing or editing the English version as it is translated.

**Comment by changkun** [comment]
@azjkjensen I am grateful to hear that you can help. Sure, I will notify you when the English version is ready :)

**Comment by NietzscheCoder** [comment]
Any updates on this?

**Comment by changkun** [comment]
@NietzscheCoder I feel sorry for my delay, it is quite busy in my recent couple of months.

I just arranged a chunk of time to work on this book in August. I hope this message helps you a little.

**Comment by NietzscheCoder** [comment]
@changkun Anyways, reading the book on github is automatically translated by Chrome..What code snippet would it try to translate as stated by some guy above?

**Comment by changkun** [comment]
@NietzscheCoder I think all chapters encouters the issue of translated code snippet.

I will patch a readable English version asap.

**Comment by NietzscheCoder** [comment]
Yes please do that mate, sometimes the grammar is also not converted properly by Chrome.

**Comment by Puthranps** [comment]
Any update on the translation?

**Comment by changkun** [comment]
@Puthranps I only have limited spare time for this work, translation is still in progress. Sorry for any inconvenience.

Probably you noticed that C++20 is under feature freeze phase, I am considering migrating this book directly to C++20 with a comprehensive module and coroutine feature introduction.

Thank you for your understanding.

**Comment by changkun** [comment]
To whom it may concern:

After the deployment of b12e03e, I am happy to announce that the book has completely translated in English, and the repository has switched to English as the default repository language.
Now you should be able to read the book in English via the following approaches:

- [GitHub Online](https://github.com/changkun/modern-cpp-tutorial/blob/master/book/en-us/toc.md)
- [PDF document](https://changkun.de/modern-cpp/pdf/modern-cpp-tutorial-en-us.pdf)
- [Website](https://changkun.de/modern-cpp)

The recent extensive not only include the translation of the originally written book but also introduces many new updates on the book's content, e.g. C++ atomic and memory model, etc.

After 1.5 years of making the book open-source, I hereby appreciate everyone who was involved in this issue and helping translate this book in English. The book will never be translated without all of you. Unfortunately, you need aware that there are still huge improvements regarding the language of the book and many many many missing features that are still not described in the book. It will be so grateful someone you who still interested in the book could find your free time to refine the language as well as the content, which refers to #1.

I am going to close this issue now and hope that all of you have a fantastic carrier path in modern C++.

Thank you and cheers,
Changkun Ou
