### ISSUE TITLE
范型lambda表达式 -> 后少返回自动类型推断关键字auto

### ISSUE THREAD

**Issue by jasonpp** [changkun/modern-cpp-tutorial#124]
## Actual Description

- File Path: for example, `book/en-us/02-usability.md`
- Original paragraph:

```
A copy of the original paragraph
```

## Expected Description

```
A modified paragraph
```

## Attachments

Attach screenshot or files if necessary.

---

## 实际描述

- 文件路径：例如，book/zh-cn/02-usability.md
- 原文段落：

```
复制原文段落
```

## 预期描述

```
修改后的段落
```

## 附图

必要时，请附上相关截图

**Comment by jasonpp** [comment]
auto add = [ ] (auto x, auto y ) -> **auto** { // 缺少auto关键字
return x + y;
};

**Comment by changdingfang** [comment]
这个auto关键字可以省略

**Comment by changkun** [comment]
As mentioned above, the auto is optional since c++14
