### ISSUE TITLE
Thread 原子操作和内存模型章节中有错别字，感谢作者让我重拾C++

### ISSUE THREAD

**Issue by jasonpp** [changkun/modern-cpp-tutorial#125]
## Actual Description

- File Path: for example, `book/en-us/02-usability.md`
- Original paragraph:

```
A copy of the original paragraph
```

## Expected Description

```
A modified paragraph
```

## Attachments

Attach screenshot or files if necessary.

---

## 实际描述

- 文件路径：例如，book/zh-cn/02-usability.md
- 原文段落：

```
复制原文段落
```

## 预期描述

```
修改后的段落
```

## 附图

必要时，请附上相关截图

**Comment by jasonpp** [comment]
仍然可能收 CPU 的乱序执行 -> 仍然可能**受**CPU的乱序执行。

**Comment by changkun** [comment]
pr welcome
