### ISSUE TITLE
重写覆盖写成了重载

### ISSUE THREAD

**Issue by cooper-zhzhang** [changkun/modern-cpp-tutorial#140]
2.6章的显示需函数重载
其实不是重载 
1:重载是在同一个作用域内 这个是发生在基类和派生类之间
2:重载是参数有所不同,但void Base::foo(int); 和SubClass::foo(int);的参数完全相同
关于重写(override)和重载(overload)在<<c++ primer >>有详细的解释 手头没书 无法给出具体的页数.

**Comment by changkun** [comment]
Please submit your issue that subject to the issue template
