### ISSUE TITLE
Use Bookdown to Build the Book in gitbook, epub and PDF with Ease

### ISSUE THREAD

**Issue by TianyiShi2001** [changkun/modern-cpp-tutorial#142]
I suggest using [bookdown](https://bookdown.org/), which makes it easy to render the book in gitbook (which can be easily deployed to GitHub pages), LaTeX (PDF) and epub, along with many other nice features, as an real example, you could visit [my book](https://tianyishi2001.github.io/cpp4r/). However, this requires R and R Studio. If you like the output but don't want to install another IDE just for building the book, I could volunteer to update the output monthly.

GitBook Output (of this book):

![image](https://user-images.githubusercontent.com/38644266/99160426-72ddd500-2711-11eb-9cbd-a272bcac031c.png)

PDF (LaTeX) output:

![image](https://user-images.githubusercontent.com/38644266/99160446-aa4c8180-2711-11eb-8cef-16e7330f1117.png)

**Comment by changkun** [comment]
It seems that it's just another wrapper of pandoc. What's the core difference from what we have here?
