### ISSUE TITLE
error: expected unqualified-id before ‘[’ token      auto [x, y, z] = f();           ^

### ISSUE THREAD

**Issue by mathpopo** [changkun/modern-cpp-tutorial#166]
#include <iostream>
#include <tuple>
#include <string>

#include <iostream>
#include <tuple>

std::tuple<int, double, std::string> f() {
    return std::make_tuple(1, 2.3, "456");
}

int main() {
    auto [x, y, z] = f();
    std::cout << x << ", " << y << ", " << z << std::endl;
    return 0;
}

**Comment by mathpopo** [comment]
cmake_minimum_required(VERSION 3.17)
project(untitled2)

set(CMAKE_CXX_STANDARD 20)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -g -Wall -Wno-unused-variable -pthread")

add_executable(untitled2 main.cpp)

**Comment by changkun** [comment]
Please fill your issue using the provided issue templates.
