### ISSUE TITLE
一些疑问🤔️

### ISSUE THREAD

**Issue by ichdream** [changkun/modern-cpp-tutorial#167]
## 在网上看到一些跟书中大量重复，相似的内容，不知道到底哪个是原创？
例如：
关于第2章语言可用性的强化：
这篇csdn博客跟作者的内容大量重复，但是这篇博客2016年就存在了，并标明根据实验楼的课程整理而来。
看了实验楼这门课的作者，叫欧龙崎，不知道跟作者是什么关系？

![image](https://user-images.githubusercontent.com/11766177/103842343-aebd6700-50d0-11eb-97e2-31e5454f9ca3.png)

![image](https://user-images.githubusercontent.com/11766177/103842485-0065f180-50d1-11eb-9514-58fb437d9f45.png)

![image](https://user-images.githubusercontent.com/11766177/103847264-c863ac00-50da-11eb-9bde-40615737e2d8.png)

**以下为疑似原创链接：**
- csdn课程笔记：https://blog.csdn.net/taoyanqi8932/article/details/53186055
- 实验楼课程：https://www.lanqiao.cn/courses/605
- 知乎链接：https://zhuanlan.zhihu.com/p/22283367

**另外，作者采用MIT开源协议，如果大量引用，摘抄别问的原创知识是否应该注明出处？或者获取原创作者的许可及授权？**

**Comment by changkun** [comment]
你好，欧龙崎就是我早期使用的网名（在我个人的博客的[介绍页](https://blog.changkun.de/about/)中有提到）。如果需要验证真伪，我也可以去实验楼把这个账号作者的名称改成欧长坤。

早在 2016 年时，这本书创作是以  11/14 为写作目标（当时 C++17 离定稿尚早）。当时我在实验楼实习，写作初期就已经跟实验楼的 CEO 确认过许可，即此书能以个人非商业名义发布开源（所以你能够看到实验楼里面我写过的一些其他 C++ 的相关课程是没有开源出来的，因为那些内容是严格的付费商业内容）。后来我从实验楼离职后，对这本书做了一些进一步的修订和更新，但已经跟之后实验楼所维护的版本产生了分支（例如某些 typo 在这里没有得到修复但那边却被修复了）。

至于 CSDN 上乃至其他任何平台上的发布内容均未联系我本人取得过授权。

保持此 issue 打开，留出一个星期发表任何其他疑问，并欢迎进一步质询。

**Comment by ichdream** [comment]
原来如此，感谢解答🤔

**Comment by changkun** [comment]
Close due to the confirmation.
