### ISSUE TITLE
example of "default template parameters", chapter02 could be misleading

### ISSUE THREAD

**Issue by RongchunYao** [changkun/modern-cpp-tutorial#169]
原文第二章关于默认模板参数的优点的示例代码：
// c++11 version
template<typename T, typename U>
auto add(T x, U y) -> decltype(x+y) {
    return x+y;
}
// Call add function
auto ret = add<int, int>(1,3);

该示例代码并不能体现出默认模板参数的作用，因为示例代码即使不指定出参数类型，也可以通过模板参数自动推倒得到。原文的 “要使用 add，就必须每次都指定其模板参数的类型” 这句话可能引发误导。

**Comment by shiwenwang** [comment]
Yes. The compiler can infer template arguments from the function arguments, it's not necessary to specify the type of template when it happens.
So, `auto ret = add(1,3);` and `auto ret = add<>(1,3);` are same with `auto ret = add<int, int>(1,3);`.

However, things are different if `add` is a struct or a class.
A sample:
```cpp
template<typename T, typename U=float>
struct add {
  constexpr auto operator()(const T &lhs, const U &rhs) const  {
    return lhs + rhs;
  }
};
auto ret = add<int>(1, 3);  // we must specify the first type at leaset.
```

**Comment by changkun** [comment]
Suggested changes are welcome.

**Comment by changkun** [comment]
As #194 has deleted this section, I think we can simply close this issue.

(Please clarify if there is anything needs a change)
