### ISSUE TITLE
Need more elaboration on "constexpr" and "const"

### ISSUE THREAD

**Issue by drelatgithub** [changkun/modern-cpp-tutorial#17]
The following code in `2.02.constexpr.cpp`:
```
    int len = 10;
    const int len_2 = len + 1;
    char arr_4[len_2];
```
seems non-standard, because the const integral type `len_2` can be treated as a constant expression only if it is initialized by a constant expression, but `len + 1` is not a constant expression, so `len_2` is NOT a constant expression (despite the fact that it is a `const` variable), and thus it cannot be used to specify the size of an array. However, both gcc and clang allow arrays of variable length as an extension, but as for a tutorial for C++11/14/17 standard, this kind of behavior should not be encouraged. Also, if you add `-pedantic` option to clang, a warning should be generated.

I really love to see more elaborations on the relationship between `const` and `constexpr` as it would easily confuse anyone new to modern C++. Personally I like the top answer in this question <https://stackoverflow.com/questions/14116003/difference-between-constexpr-and-const>, so it would be really nice if you could incorporate some of the content in the tutorial.

By the way, I've learned a lot from your tutorial. So thank you and keep up the good work!

**Comment by changkun** [comment]
Hi @drelatgithub , I really appreciate you correct my misunderstanding regarding `const` and `constexpr` for so long. This is an unforgivable mistake that must be fixed soon, I feel guilty that provides a wrong explanation of them. I will rephrase this section ASAP.
