### ISSUE TITLE
Is content of chapter 7 Release/Acquire model correct????

### ISSUE THREAD

**Issue by FischLu** [changkun/modern-cpp-tutorial#174]
## Actual Description

- File Path: `07-thread.md`
- Original paragraph:

As you can see, `std::memory_order_release` ensures that the write behavior after it does not occur before the release operation, which is a forward barrier, and `std::memory_order_acquire` ensures that its previous write behavior does not occur after this acquisition operation, there is a backward barrier. 

## Expected Description

according to [cppreference](https://en.cppreference.com/w/cpp/atomic/memory_order#Release-Acquire_ordering), I think this description is the other way around, which should be:

As you can see, `std::memory_order_release` ensures that the write behavior **before** it does not occur **after** the release operation, which is a **backward** barrier, and `std::memory_order_acquire` ensures that its **subsequent** **read/write** behavior does not occur **before** this acquisition operation, **which** is a **forward** barrier.

**Comment by changkun** [comment]
Previously reported in #159. (Needs a careful review on this.)
