### ISSUE TITLE
Lambda可以通过引用捕获unique_ptr

### ISSUE THREAD

**Issue by Dw9** [changkun/modern-cpp-tutorial#179]
文件：modern-cpp-tutorial/book/zh-cn/03-runtime.md
原文段落：

> #include <iostream>
> #include <utility>
> 
> int main() {
>     auto important = std::make_unique<int>(1);
>     auto add = [v1 = 1, v2 = std::move(important)](int x, int y) -> int {
>         return x+y+v1+(*v2);
>     };
>     std::cout << add(3,4) << std::endl;
>     return 0;
> }

> 在上面的代码中，important 是一个独占指针，是不能够被捕获到的，这时候我们需要将其转移为右值， 在表达式中初始化。

建议修改：
 在上面的代码中，important 是一个独占指针，是不能够被“=”按值捕获到的，这时候我们可以将其转移为右值， 在表达式中初始化。

考虑以下代码：

> #include <iostream>
> #include <utility>
> 
> int main() {
>     auto important = std::make_unique<int>(1);
>     auto add = [&,v1 = 1](int x, int y) -> int {
>         return x+y+v1+(*important);
>     };
>     std::cout << add(3,4) << std::endl;
>     return 0;
> }
不讨论其他问题的情况下，unique_ptr 实际上可以通过引用捕获到 ~

**Comment by changkun** [comment]
Why this is closed? I would encourage you to send a pull request.

**Comment by Dw9** [comment]
Thank you for putting a lot of thought into this, I thought I deliver mistakenly so that it’s not necessary to correct.
