### ISSUE TITLE
Busted creation of revision.tex

### ISSUE THREAD

**Issue by vonbrand** [changkun/modern-cpp-tutorial#188]
Building the PDF fails, due to a `revision.tex` file with double '\\'.

Attached a patch against v2.0.0-alpha-64-g645fa62 (generated by `git`).
[patch.txt](https://github.com/changkun/modern-cpp-tutorial/files/6525391/patch.txt)

**Comment by ankitcr7-afk** [comment]
I would like to resolve this issue. As I am a beginner would you mind guiding what I actually have to do

**Comment by changkun** [comment]
Oh, sorry for the late response.

I think this happens when you are using a Windows system. Maybe if you could switch to a different system, such as Linux or macOS?

**Comment by ankitcr7-afk** [comment]
> Oh, sorry for the late response.
> 
> I think this happens when you are using a Windows system. Maybe if you could switch to a different system, such as Linux or macOS?

Actually I'm on manjaro os which is a Linux distro

**Comment by changkun** [comment]
Interesting. I just tried on my Ubuntu Linux, it does not occur, maybe because of different behavior of the echo command?

**Comment by ankitcr7-afk** [comment]
> Interesting. I just tried on my Ubuntu Linux, it does not occur, maybe because of different behavior of the echo command?

Yea it can be
