### ISSUE TITLE
Update PDF

### ISSUE THREAD

**Issue by Nikhil0504** [changkun/modern-cpp-tutorial#191]
## Question

Can we update the PDF with all the grammatical changes to make it up-to-date with repo?
I’ll probably pull up a PR for that if possible.

## 问题描述

请在此描述你的问题，提问前请参考[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

**Comment by changkun** [comment]
See https://github.com/changkun/modern-cpp-tutorial/blob/master/CONTRIBUTING.md
