### ISSUE TITLE
Is there a Russian language?

### ISSUE THREAD

**Issue by melisha-git** [changkun/modern-cpp-tutorial#195]
I am Russian speaking, I would like to know how to find a book in Russian?

**Comment by melisha-git** [comment]
In Russian please?

**Comment by changkun** [comment]
Hi, thanks for asking. The book was written in Chinese and then translated into English. These are the two languages supported at the moment. If there is a translation from community, it also welcome.

See previous attempts: #82, #168, ...

**Comment by melisha-git** [comment]
Hi, thanks for answer.
