### ISSUE TITLE
website: exercise folder returns 403

### ISSUE THREAD

**Issue by xBLACKICEx** [changkun/modern-cpp-tutorial#198]
## 实际描述
**这里**链接错误显示为403
- 文件路径：https://changkun.de/modern-cpp/zh-cn/00-preface/#相关代码
- 原文段落：
不妨读一读随书附上的源码，你可以在**这里**中找到书中介绍过的全部的源码，所有代码按章节组织，文件夹名称为章节序号。

错误链接地址
https://changkun.de/modern-cpp/exercises/

## 附图

![image](https://user-images.githubusercontent.com/51036094/126068726-db5e2f7c-4530-4b00-a58a-16b1c5a4a3d9.png)

**Comment by changkun** [comment]
PR welcome.

**Comment by changkun** [comment]
Should be resolved now through https://github.com/changkun/nginx-autoindex.

Closing.
