### ISSUE TITLE
website: improve readability

### ISSUE THREAD

**Issue by gdh1995** [changkun/modern-cpp-tutorial#201]
## Motivation

Please briefly describe your motivation.

## Requirements

Please list all of your suggestions.

---

## 动机

我访问了在线版 https://changkun.de/modern-cpp/ 的中文版，发现代码字体非常细，读起来很吃力，换成 PDF 版本才好了些（但对我来说还是不够粗）。

## 需求说明

希望提供一个模式，可以更换代码排版使用的字体到笔画更粗的字体，或者让用户自己填？如果同时能更换正文字体那就更好了。

单纯的横向加粗应该不够，比如一横加粗完还是一横，仍然不够显眼。我希望的用是黑体、雅黑这种无论横竖笔画都很粗的字体。

谢谢！

**Comment by changkun** [comment]
PR welcome

**Comment by gdh1995** [comment]
我本机没有`Roboto Mono`，Edge自动选了`Courier New`。我刚试了试发现`font-weight: bold;`时横线也会变粗，那就不怎么用改字体了，直接 `.code { font-weight: bold; }` 应该也行

**Comment by changkun** [comment]
I think you may use the combination of `ctrl` and `+` and zoom the page out. There is no need for readability optimization.

Close.

(Please clarify if there is a need for further discussion)

**Comment by gdh1995** [comment]
普通汉字不需要缩放，所以`Ctrl++`不是特别方便。不过我现在配置了个扩展来自动添加样式 `code, pre { font-weight: bold; }` 了。
