### ISSUE TITLE
在没有自定义初始化列表构造函数的类中，可以用初始化列表直接初始化对象吗？

### ISSUE THREAD

**Issue by YuXiang-ZhuanSun** [changkun/modern-cpp-tutorial#207]
## 实际描述

- 文件路径：book/zh-cn/02-usability.md
- 原文段落：

而对于类对象的初始化，要么需要通过拷贝构造、要么就需要使用 () 进行。 这些不同方法都针对各自对象，不能通用。

**但是又写道：**

其次，C++11 还提供了统一的语法来初始化任意的对象，例如：
```
Foo foo2 {3, 4};
```

**Comment by changkun** [comment]
请注意描述的前提，不要断章取义．前者是说 "在传统 C++ 中" ，后者是指 C++11

关于 "传统 C++" 的定义，参见序言

**Comment by YuXiang-ZhuanSun** [comment]
谢谢，我没看清楚第一段介绍指传统c++，抱歉。

我还有个问题：

其次，C++11 还提供了统一的语法来初始化任意的对象，例如：

```
Foo foo2 {3, 4};

```
**使用初始化列表初始化对象在底层是转化为调用特定构造函数吗？或者是直接按顺序初始化对象内各变量？**

**Comment by changkun** [comment]
这个得分情况讨论，具体在需要时可以查阅参考手册：

https://en.cppreference.com/w/cpp/language/list_initialization

**Comment by YuXiang-ZhuanSun** [comment]
谢谢。
