### ISSUE TITLE
auto能否进行形参类型推导？

### ISSUE THREAD

**Issue by YuXiang-ZhuanSun** [changkun/modern-cpp-tutorial#208]
## 问题描述

原文位置：/book/zh-cn/02-usability.md

你可能会思考，在介绍 auto 时，我们已经提过 auto 不能用于函数形参进行类型推导，

**但我在前文中只找到**：

从 C++ 20 起，auto 甚至能用于函数传参，考虑下面的例子：
```
int add(auto x, auto y) {
    return x+y;
}

auto i = 5; // 被推导为 int
auto j = 6; // 被推导为 int
std::cout << add(i, j) << std::endl;
```

所以auto是否能进行函数参数类型推导？？

**Comment by changkun** [comment]
这个例子已经特指 C++20 可以用于函数参数类型推导，即早期版本不能进行函数形参类型推导．
