### ISSUE TITLE
typo of memory order

### ISSUE THREAD

**Issue by wind-tangkai** [changkun/modern-cpp-tutorial#218]
## Actual Description

- File Path: for example, `book/en-us/02-usability.md`
- Original paragraph:

```
A copy of the original paragraph
```

## Expected Description

```
A modified paragraph
```

## Attachments

Attach screenshot or files if necessary.

---

## 实际描述

- 文件路径：例如，book/zh-cn/02-usability.md
- 原文段落：

```
复制原文段落
```

## 预期描述

```
修改后的段落
```

## 附图

![image](https://user-images.githubusercontent.com/5468452/145698185-d61f2f7d-1250-46fb-a025-408d2f11297e.png)

必要时，请附上相关截图

**Comment by changkun** [comment]
I don’t understand what is the typo. Please use the template to fill an issue. Close.
