### ISSUE TITLE
漏字

### ISSUE THREAD

**Issue by add358** [changkun/modern-cpp-tutorial#221]
## 实际描述

- 文件路径：例如，book/zh-cn/02-usability.md
- 原文段落：

```
而我们希望获得枚举值的值时，将必须显式的进行类型转换，不过我们可以通过重载 << 这个算符来进行输出，可以收藏下面这个代码段：
```

## 预期描述

```
而我们希望获得枚举值的值时，将必须显式的进行类型转换，不过我们可以通过重载 << 这个运算符来进行输出，可以收藏下面这个代码段：
```

**Comment by changkun** [comment]
I don't think this is a missed character. The English "operator" can be translated as "算符".
