### ISSUE TITLE
2.2 变量及其初始化 中，if初始化的设计并不是来源于Go或者其他语言，而是Bjarne Stroustrup自己的设计

### ISSUE THREAD

**Issue by YexuanXiao** [changkun/modern-cpp-tutorial#234]
Bjarne Stroustrup 所著的《C++ 语言的设计和演化》（英文版于1994年出版）的3.11.5节中写到：

>1. for语句里的声明
>...
>2. 条件语句里的声明
> 人们在谨慎地努力避免未初始化的变量，剩下的还有：
>...
>2\) 在条件语句里使用的变量：
>...
> 在1991年设计运行时的类型识别机制时，我认识到，如果允许将声明作为条件，就可以消除产生未初始化变量的后遗症情况，例如：
```cpp
if(Tok*ct = gettok()) {
    // ct is in scope here
}

// ct is not scope here
```
>这个特征并不只是一种减少打字输人的小窍门，它也是局部化思想的一个直接推论。通过把 一个变量的声明、它的初始化以及对初始化结果的测试组合到一起，我们就得到了一种紧凑 的表达方式，它能帮我们清除由于变量没有初始化就被使用而产生的错误。通过把这种变量 的作用域限制到有关条件所控制的语句里，我们也解决了重新赋一子这些变量其他用途的问题， 以及在已经认为它们不再存在之后又不经意地使用的问题。这也就清除了另一个较小的错误 根源。 允许在表达式里写声明的灵感来自表达式语言―特别是Algol 68。我“记得”Algol 68 的声明产生值，所以就基于这点做了我的设计。后来我才发现自己的记忆是错误的，声明实 际上是在Algol 68里仅有的几种不产生值的结构之一。我向Charles Lindsey提出这个问题，得 到的回答是“甚至Algol 68也有些瑕疵，在某些地方它并不是完全正交的”。我想这不过是证 明了一个语言并不必无愧于它自己的理想，也照样可以为人提供灵感。 如果我是从一张白纸出发去设计语言，我将遵循Algol 68的方式，让每个语句或者声明都 是表达式，都产生一个值。我将禁止未初始化的变量，并抛弃在一个声明里说明多个变量的 思想。当然事情很清楚，这些想法己经远远超出了能够被C+＋接受的范围。 

**并且允许在if内声明变量不仅仅是为了防止命名冲突，更是为了约束变量的生命周期：itr 这个变量只在 if 块内使用，但是却不得不定义在 if 块的外面**

## 实际描述

- 文件路径：book/zh-cn/02-usability.md
- 原文段落：变量及其初始化

```
...

在上面的代码中，我们可以看到 itr 这一变量是定义在整个 main() 的作用域内的，这导致当我们需要再次遍历整个 std::vectors 时，需要重新命名另一个变量。C++17 消除了这一限制，使得我们可以在 if（或 switch）中完成这一操作：

...

怎么样，是不是和 Go 语言很像？
```

## 预期描述

```
...

在上面的代码中，我们可以看到 itr 这一变量是定义在整个 main() 的作用域内的， itr 这个变量只在 if 块内使用，但是却不得不定义在 if 块的外面，这违反了 C++ 的一个追求：用作用域约束变量的生命周期。C++ 在设计之初就注意到了这个问题，但是由于历史原因并未支持这一特性。C++17 消除了这一限制，使得我们可以在 if（或 switch）中完成这一操作：
```

**Comment by changkun** [comment]
请问原文建议这一设计是来源于 Go 语言了吗？

**Comment by changkun** [comment]
我认为一个可能保留原作者写作意愿的更改是（虽然我个人主观上没有感受到两种表达的区别）：

```diff
-怎么样，是不是和 Go 语言很像？
+怎么样，Go 语言和这个写法是不是很像？
```

直接删除是不被鼓励的。
