### ISSUE TITLE
第6章的习题设置不合理

### ISSUE THREAD

**Issue by cangyin** [changkun/modern-cpp-tutorial#253]
第6章习题未给出完整语境，成员函数 start() 与 parse_request() 分别要完成什么任务未给出清晰定义，只要求 “使得服务器模板使用者可以如下指定路由”，然而答案中路由相关的逻辑却在 respond() 函数中。最后留给读者的疑难就成了：start() 要实现什么？parse_request() 不实现路由逻辑应该实现什么？

**Comment by changkun** [comment]
It is intended to give problems without a clear definition. A qualified engineer should be capable of narrowing down fuzzy descriptions into well-defined problem spaces and be able to propose multiple solutions concerning multiple trade-offs. If you consider the objective of the exercise unclear, please ask more specific questions. Thanks.
