### ISSUE TITLE
关于普通重载和override的一个区别

### ISSUE THREAD

**Issue by lingkerio** [changkun/modern-cpp-tutorial#264]
## 实际描述

- 文件路径：book/zh-cn/02-usability.md
- 原文段落：

```
override
当重载虚函数时，引入 override 关键字将显式的告知编译器进行重载，编译器将检查基函数是否存在这样的虚函数，否则将无法通过编译
```

## 预期描述

```
override
当重载虚函数时，引入 override 关键字将显式的告知编译器进行重载，编译器将检查基函数是否存在这样的函数签名一致的虚函数，否则将无法通过编译
```

## 附图

<img width="511" alt="image" src="https://user-images.githubusercontent.com/112792583/236609898-e8f48dae-6e9e-48ea-9f86-c8aeea0c897b.png">

**Comment by changkun** [comment]
PR welcome
