### ISSUE TITLE
第二章 尾返回类型推导 “我们已经提过 auto 不能用于函数形参进行类型推导”

### ISSUE THREAD

**Issue by yangyagami** [changkun/modern-cpp-tutorial#266]
## 问题描述

“我们已经提过 auto 不能用于函数形参进行类型推导” 这里是否是表述错误呢？

**Comment by Ding-yixia** [comment]
是的，他这里应该有点问题，C++20 之后可以进行函数形参类型推导

**Comment by frederick-vs-ja** [comment]
C++14 中 `auto` 已经可以用于函数函数模板形参推导，只是局限于泛型 lambda 中。
