### ISSUE TITLE
网页加载速度

### ISSUE THREAD

**Issue by iscas-zac** [changkun/modern-cpp-tutorial#270]
## 动机

官网的加载过于缓慢，阅读体验比较尴尬。

## 需求说明

不知道是不是服务器在国外的原因？现在 github pages 之类的服务感觉国内访问还快一些。如果网页没什么动态需求的话，是不是可以在这类静态服务器上放个镜像？

**Comment by changkun** [comment]
您可以下载其他版本进行阅读
