### ISSUE TITLE
C++ 中不允许将 `NULL` 定义为 `((void*)0)`

### ISSUE THREAD

**Issue by Mq-b** [changkun/modern-cpp-tutorial#274]
- 文件路径：book/zh-cn/02-usability.md

> nullptr 出现的目的是为了替代 NULL。在某种意义上来说，传统 C++ 会把 NULL、0 视为同一种东西，这取决于编译器如何定义 NULL，***有些编译器会将 NULL 定义为 `((void*)0)`***，有些则会直接将其定义为 0。

- **C 中，宏 NULL 可以拥有类型 `void*`，但这在 C++ 中不允许，因为空指针常量不能具有该类型**。这是明确规定的。

应该改为

> nullptr 出现的目的是为了替代 NULL。C++ 可能会把 NULL、0 视为同一种东西，这取决于编译器如何定义 NULL，***宏 NULL 是由实现定义的[空指针常量](https://zh.cppreference.com/w/cpp/language/pointer#.E7.A9.BA.E6.8C.87.E9.92.88)***。而值为零的整数字面量就是*空指针常量*。

**Comment by frederick-vs-ja** [comment]
同时还存在的问题是 `NULL` 并不是编译器定义的。

**Comment by Mq-b** [comment]
区分标准库（如主流 libstdc++、MSVC STL、libc++）与编译器，对于不少人来说还是过于复杂了，很多表述的确不严谨，能修改自然更好。
