### ISSUE TITLE
描述 `std::mutex` 的用词奇怪，应当更改

### ISSUE THREAD

**Issue by Mq-b** [changkun/modern-cpp-tutorial#284]
- 文件路径：book/zh-cn/07-thread.md

[web 位置](https://changkun.de/modern-cpp/zh-cn/07-thread/#7-2-%E4%BA%92%E6%96%A5%E9%87%8F%E4%B8%8E%E4%B8%B4%E7%95%8C%E5%8C%BA)

原文：

> std::mutex 是 C++11 中最基本的 mutex 类，通过实例化 std::mutex 可以创建互斥量

这句话的感觉基本就是胡言乱语，虽然我能明白它要表达的意思，但这是因为我本来就知道。

1. “《***std::mutex 是最基本的 mutex***》”，后文又重新使用了中文的“互斥量”，要么就都互斥量即可，何必如此抽象。

2. “*通过实例化 std::mutex 可以创建互斥量*”，我本人一直不喜欢这种实例化 xxx 类型创建 xxx，何不直接说：**可以使用 `std::mutex` 类型创建互斥量对象**

总而言之，简单的描述为：

- std::mutex 是 C++11 引入的最基本的互斥量类型，**可以使用 `std::mutex` 创建互斥量对象**。

**Comment by changkun** [comment]
Thanks and PR welcome

**Comment by frederick-vs-ja** [comment]
我们最好审核一下全书的“实例化”。按照标准的话只有模板化实体才有实例化。

**Comment by Mq-b** [comment]
我觉得这来自于目前广泛用词的不严谨与不统一，比如经常有说法是：

> 我编写了一个类型 T，并实例化了一个对象...

等等类似。我觉得这也源自对于 **“实例”与“实例化”无法正确区分**。

前者常常表达式：“**对象实例**”，而后者，很多人无法意识到这实际上是个 C++ 中的专门术语。

大概是也就是这样让“实例”与“实例化”混淆，使用者大多也不清楚这些用词。
