### ISSUE TITLE
“堆栈回退”我认为您要表达的是：“栈回溯”

### ISSUE THREAD

**Issue by Mq-b** [changkun/modern-cpp-tutorial#285]
- 文件路径：book/zh-cn/07-thread.md

[web 位置](https://changkun.de/modern-cpp/zh-cn/07-thread/#7-2-%E4%BA%92%E6%96%A5%E9%87%8F%E4%B8%8E%E4%B8%B4%E7%95%8C%E5%8C%BA)

原文：

> 由于 C++ 保证了所有栈对象在生命周期结束时会被销毁，所以这样的代码也是异常安全的。 无论 critical_section() 正常返回、还是在中途抛出异常，都会引发***堆栈回退***，也就自动调用了 unlock()。

首先“**栈回溯**”这个词更加常见与明确，其次，“堆栈”这个词，非常不好，参见：https://github.com/Qihoo360/safe-rules/issues/54

且我觉得有必要强调一句话：

- 没有捕获[抛出的异常](https://zh.cppreference.com/w/cpp/language/throw)（此时由实现定义是否进行栈回溯）

因为原文的描述在我看来暗示了所有情况都会进行栈回溯。

**Comment by changkun** [comment]
Thanks and PR welcome
