### ISSUE TITLE
9.2 noexcept部分代码或许存在问题

### ISSUE THREAD

**Issue by razerhell** [changkun/modern-cpp-tutorial#33]
9.2 noexcept 修饰完一个函数之后能够起到封锁异常扩散的功效，如果内部产生异常，外部也不会触发。

我的理解是不会触发异常而执行catch中的代码，
如果我的理解正确的话：

之后给出的代码好像并不能体现出这一特性，

没有noexcept修饰符的my_throw()抛出了异常，但执行了catch中的代码
2，没有noexcept修饰符的non_block_throw()抛出了异常，也执行了catch中的代码
3，具有noexcept修饰符的block_throw()函数并没有抛出异常，当然也没有触发catch中的代码
4，于是我自做主张为my_throw() 增加了noexcept操作符使其声明变为
    void may_throw() noexcept
    这样的情况下：
    4-1，编译器会发出警告（ warning C4297: “may_throw”: 假定函数不引发异常，但确实发生了）
    以及（note: 在函数上指定了 __declspec(nothrow)、throw()、noexcept(true)或 noexcept）（vs2017）
    4-2，运行期间，程序直接异常退出。与我理解相反地，这个异常不能被try...catch语句捕捉，或许这才 
    你所要表达的“如果内部产生异常，外部也不会触发（try...catch语句）。”？

**Comment by razerhell** [comment]
由新给出的例子进行进一步测试。将 void no_throw() noexcept 中的 noexcept 去除，使其变为 void no_throw()，输出变成了no_throw()  noexcept? false，由此可以推断noexcept(fun())的输出只与原函数后是否跟了noexcept相关。同时，在这几个测试函数中加入输出语句，运行结果表明noexcept(fun())并不会对函数进行调用，函数根本就不会抛出异常，也不存在外界是否会对其进行捕获或处理的问题。

**Comment by changkun** [comment]
noexcept 作为运算符时候，会在编译期对表达式进行检查，同时不会对表达式进行直接求值。相反，从 C++17 起，noexcept 运算符为 true 的唯一条件就是表达式的潜在异常集合为空则结果为 true，否则为 false。对于 noexcept 修饰过的函数通过 noexcept 运算符时得到了 false 的结果，这是不可能的。说明的就是：noexcept 在作为指定符时，对异常有阻断作用。如果一个函数没有被 noexcept 修饰，它可能抛出异常也可能不抛出异常，这是不确定的，所以潜在异常集合不空，因此结果始终未 false。
