### ISSUE TITLE
关于 weak_ptr 的描述感觉不是很严谨

### ISSUE THREAD

**Issue by SpacelessL** [changkun/modern-cpp-tutorial#34]
> std::weak_ptr 没有 * 运算符和 -> 运算符，所以不能够对资源进行操作，它的唯一作用就是用于检查 std::shared_ptr 是否存在，expired() 方法在资源未被释放时，会返回 true，否则返回 false

这里读起来的感觉更像是只有expired()方法，至少lock应该不只是有检查std::shared_ptr是否存在这一个作用

**Comment by changkun** [comment]
这个地方确实表述不够严谨，应该这么叙述：

std::weak_ptr 没有 * 运算符和 -> 运算符，所以不能够对资源进行操作，它的唯一作用就是用于检查 std::shared_ptr 是否存在。其 expired() 方法能够在资源未被释放时，会返回 true，否则返回 false
