### ISSUE TITLE
函数和函数指针这一部分的表述不是非常准确

### ISSUE THREAD

**Issue by yaozhongxiao** [changkun/modern-cpp-tutorial#38]
3.2 函数对象包装器

函数和函数指针这一部分的表述不是非常准确，如下的解释感觉比较精确，是否可以参考
https://www.jianshu.com/p/6ecfd541ec04

@changkun

**Comment by changkun** [comment]
你好 这部分内容是笔者多年前写下的了 目前比较忙还没有时间审阅到这个部分 欢迎你提 PR 修改。
