### ISSUE TITLE
提问：什么情况下需要手动释放 std::vector 中资源

### ISSUE THREAD

**Issue by isLishude** [changkun/modern-cpp-tutorial#54]
>...相比堆内存中的 std::vector，我们就能够灵活的访问这里面的元素，从而获得更高的性能；同时正是由于其堆内存存储的特性，有些时候我们还需要自己负责释放这些资源。https://github.com/changkun/modern-cpp-tutorial/blob/master/book/zh-cn/04-containers.md

我问过一些人，都是回答我释放资源是 std::vector 析构函数自动完成的，不需要手动释放。

请问什么时候需要手动释放？

我想了想，是说元素是指针的情况吗？

**Comment by changkun** [comment]
您好，这里是指当我们对一个 `std::vector` 进行 `resize` 或者 `clear` 操作时，附着的内存仍然没有被释放。在 C++11 中可以通过 `shrink_to_fit` 成员函数来手动释放额外的内存。

感谢提问，建议进一步提交 PR 并完善文中的相关场景的描述。
