### ISSUE TITLE
关于线程方面的疑问

### ISSUE THREAD

**Issue by fawdlstty** [changkun/modern-cpp-tutorial#58]
https://github.com/changkun/modern-cpp-tutorial/blob/master/book/zh-cn/07-thread.md
里面7.4的代码，
```
 while (!notified) { // 循环避免虚假唤醒
    cond_var.wait(lock);
}
```
notefied变量非volatile，是否存在这种问题：编译器优化时将其放置在寄存器中，线程更改变量时没有更新寄存器的变量，导致卡死

**Comment by changkun** [comment]
我的理解是不会出现这种问题，这里的内存顺序是通过 mutex 保障的，因而具备缓存一致性。

**Comment by fawdlstty** [comment]
- -    这个和mutex无关。另外那你觉得volatile关键字有啥含义么

**Comment by fawdlstty** [comment]
![20190125231016](https://user-images.githubusercontent.com/7323999/51754121-73e5e280-20f6-11e9-898e-db70118b8637.jpg)
https://baike.baidu.com/item/volatile

**Comment by changkun** [comment]
我我认为前面已经解释清楚了，你可以多了解一下缓存的一致性原理

**Comment by changkun** [comment]
@fawdlstty 非常抱歉，刚注意到这个 issue 还有两条跟进回复，可能通知太多之前给忽视了。

是这样的，在文中的例子中，我们使用了 std::mutex，因此任何 lock.unlock() 之前的操作，都能够被 lock.lock() 后的操作观察到，即 release-acquire 同步。你所说的 volatile 是不可能发生的。

**Comment by joyqat** [comment]
放一个结果
![screenshot](https://user-images.githubusercontent.com/10184445/61339907-8c97af80-a872-11e9-8c1e-03750981ba43.png)

即使没有volatile，编译器也不会把这里的循环条件变量放在寄存器中。
https://godbolt.org/z/36FxPY

**Comment by changkun** [comment]
@joyqat 你说的没错，从实际汇编中观察也是一种做法，但这只能说明在一种编译条件下是这样的结果。
如果是通过标准来解释的话，仍应当是通过 mutex lock 的顺序一致性进行说明的。
