### ISSUE TITLE
第 5 章 标准库：指针的一处笔误

### ISSUE THREAD

**Issue by freezer-glp** [changkun/modern-cpp-tutorial#59]
图书网站版：
https://changkun.de/modern-cpp/book/05-pointers/index.html#5-2-std-shared-ptr

如图：
![image](https://user-images.githubusercontent.com/5022695/52037150-2ab7e780-2569-11e9-9ee8-494ac4adf999.png)
`use_count`写成了`get_count`

**Comment by changkun** [comment]
@freezer-glp The website server negotiate with a browser to use a local cache, please handcrafted refresh (command+R) to refresh the site or clear your local caches. You will see the content that up-to-date. Thanks for your reporting.
