### ISSUE TITLE
第二章 2.3类型推导 auto示例代码有误

### ISSUE THREAD

**Issue by pyyzcwg2833** [changkun/modern-cpp-tutorial#66]
## 实际描述

- 文件路径：例如，book/zh-cn/02-usability.md
- 原文段落：
```
auto i = 5;              // i 被推导为 int
auto arr = new auto(10); // arr 被推导为 int *
```

## 预期描述

```
auto i = 5;              // i 被推导为 int
auto arr = new int(10); // arr 被推导为 int *
```

## 附图

必要时，请附上相关截图
![屏幕快照 2019-04-23 11 18 33](https://user-images.githubusercontent.com/24390069/56550943-9c785e00-65b9-11e9-9750-9f00d0a5f15f.png)

**Comment by changkun** [comment]
这里不是错误。

第二个 `auto` 自动推导了 `arr` 的类型与 `10` 保持一致，即 `auto(10)` 等价于 `int(10)`，
由于 `new` 使得 10 被分配在堆上，从而 `arr` 中第一个 `auto` 被推导为 `int *`。

参见：http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3690.pdf，5.3.4 小节中的描述

> If the auto type-specifier appears in the type-specifier-seq of a new-type-id or type-id of a new-expression, the new-expression shall contain a new-initializer of the form
>
> > ( assignment-expression )
>
> The allocated type is deduced from the new-initializer as follows: Let e be the assignment-expression in the new-initializer and T be the new-type-id or type-id of the new-expression, then the allocated type is the type deduced for the variable x in the invented declaration (7.1.6.4):
>
> > T x(e);
>
> [ Example:
>
> > new auto(1); // allocated type is int
> > auto x = new auto(’a’); // allocated type is char, x is of type char*
>
> —end example ]
