### ISSUE TITLE
右值引用举例错误

### ISSUE THREAD

**Issue by visvlee** [changkun/modern-cpp-tutorial#67]
## 实际描述

- 文件路径：例如，book/zh-cn/02-usability.md
- 原文段落：

```
// 防止编译器优化
A return_rvalue(bool test) {
    A a,b;
    if(test) return a;
    else return b;
}
```

## 预期描述
a,b是左值，不是右值，上面的代码会调用拷贝构造函数，不是移动构造函数，如果
要掉用移动构造，需要调用std::move()将左值转成右值

```
// 防止编译器优化
A return_rvalue(bool test) {
    A a,b;
    if(test) return std::move(a);
    else return std::move(b);
}
```

## 附图

必要时，请附上相关截图

**Comment by changkun** [comment]
你好，这里的函数名可能具备一定误导作用。你对此例子的理解有误：

1. `return_rvalue` 的目的仅仅只是为了防止编译器优化
2. `return_rvalue` 在 `main` 中的等号右边产生的返回值为将亡值，此时是右值，从而调用移动构造 `A(A&& a)`

**Comment by changkun** [comment]
你好，此处为隐式右值转换，等价于 `static_cast<A&&>(a)`，参见
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2002/n1377.htm#Moving%20from%20local%20values

**Comment by visvlee** [comment]
感谢你的解答
