### ISSUE TITLE
第三章将亡值解释错误

### ISSUE THREAD

**Issue by visvlee** [changkun/modern-cpp-tutorial#68]
## 实际描述

- 文件路径：例如，book/zh-cn/02-usability.md
- 原文段落：

```
将亡值(xvalue, expiring value)，是 C++11 为了引入右值引用而提出的概念（因此在传统 C++中，纯右值和右值是同一个概念），也就是即将被销毁、却能够被移动的值。

将亡值可能稍有些难以理解，我们来看这样的代码：
std::vector<int> foo() {
    std::vector<int> temp = {1, 2, 3, 4};
    return temp;
}

std::vector<int> v = foo();
```
原文解释如下
http://naipc.uchicago.edu/2015/ref/cppreference/en/cpp/language/value_category.html
A function call expression, if the function's return type is an rvalue reference to object type, such as std::move(val)
A cast expression to an rvalue reference to object type, such as static_cast<T&&>(val) or (T&&)val
a non-static class member access expression, in which the object expression is an xvalue
A pointer-to-member expression in which the first operand is an xvalue and the second operand is a pointer to data member.

```
将亡值可能稍有些难以理解，我们来看这样的代码：
std::vector<int> foo() {
    std::vector<int> temp = {1, 2, 3, 4};
    return std::move(temp);
}

std::vector<int> v = foo();
```

## 附图

必要时，请附上相关截图

**Comment by changkun** [comment]
文中此段的描述确实对读者具备一定迷惑性，因为所提供的代码片段中只是在描述对 xvalue 进行分类的动机，并非介绍 xvalue 自身是什么，也没有错误的说明 foo 返回得到的是 xvalue。

相反，真正的 xvalue 是在接下来一小节“右值引用和左值引用”中的代码片段进行介绍的。

欢迎 PR 改进此段内容的描述。
