### ISSUE TITLE
微信群现已可用 (WeChat group is available)

### ISSUE THREAD

**Issue by changkun** [changkun/modern-cpp-tutorial#75]
## 动机

本书现有 QQ 群，考虑 QQ 的使用频率下降，故此提供微信群。

有兴趣的读者可以使用以下二维码加入：

![7057AE1728F47BFBB4554FB507DF2B53](https://user-images.githubusercontent.com/5498964/63025656-f626d000-bea9-11e9-8720-6ea7f0d73e2d.jpg)

**Comment by hehy0r** [comment]
二维码已过期。

if/switch 变量声明强化
在传统 C++ 中，**变量的声明_在_虽然能够位于任何位置**，····

**Comment by changkun** [comment]
@hehy0r 感谢指出错误，已在 4b1181f233663105c09a8a26993dea525ecfc2fa 修正
