### ISSUE TITLE
lambda 章节：建议增加对 lambda 对象生存期（extent）的描述

### ISSUE THREAD

**Issue by patrick-yingxi-pan** [changkun/modern-cpp-tutorial#84]
## Motivation

Please briefly describe your motivation.

## Requirements

Please list all of your suggestions.

---

## 动机

请描述你提交内容建议的动机。

## 需求说明

请描述你提交内容建议的详单，例如具体是增加哪个知识点的说明。

**Comment by changkun** [comment]
dup #85
