### ISSUE TITLE
book/lambda: 建议补充被捕获对象生存期

### ISSUE THREAD

**Issue by patrick-yingxi-pan** [changkun/modern-cpp-tutorial#85]
## Motivation

Please briefly describe your motivation.

## Requirements

Please list all of your suggestions.

---

## 动机

请描述你提交内容建议的动机。

## 需求说明

请描述你提交内容建议的详单，例如具体是增加哪个知识点的说明。

**Comment by changkun** [comment]
请根据模板填写更加详细的说明以达到阐明详细需求的目的。

**Comment by changkun** [comment]
close due to age
