### ISSUE TITLE
zh-cn/07-thread: typo in memory order acquire

### ISSUE THREAD

**Issue by ZeroOcyc** [changkun/modern-cpp-tutorial#96]
## Actual Description

- File Path: for example, `book/en-us/02-usability.md`
- Original paragraph:

```
A copy of the original paragraph
```

## Expected Description

```
A modified paragraph
```

## Attachments

Attach screenshot or files if necessary.

---

## 实际描述

- 文件路径：https://changkun.de/modern-cpp/zh-cn/07-thread/index.html
- 原文段落：

```
3. 释放/获取模型：在此模型下，我们可以进一步加紧对不同线程间原子操作的顺序的限制，在释放 std::memory_order_release 和获取 std::memory_order_acquire 之间规定时序，即发生在释放操作之前的所有写操作，对其他线程的任何获取操作都是可见的，亦即发生顺序（happens-before）。

可以看到，std::memory_order_release 确保了它之后的写行为不会发生在释放操作之前，是一个向后的屏障，而 std::memory_order_acquire 确保了它之后的前的写行为，不会发生在该获取操作之后，是一个向前的屏障，对于选项 std::memory_order_acq_rel 而言，则结合了这两者的特点，唯一确定了一个内存屏障，使得当前线程对内存的读写不会被重排到此操作的前后。
```

## 预期描述
而 std::memory_order_acquire 确保了它**之后的前的**写行为  此处描述错误
```
而 std::memory_order_acquire 确保了它之前的写行为
```

## 附图

必要时，请附上相关截图

**Comment by changkun** [comment]
Thank you very much!
